//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "auth_register.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string auth_register::genText(const DrTemplateData& auth_register_view_data)
{
	drogon::OStringStream auth_register_tmp_stream;
	std::string layoutName{""};
	auth_register_tmp_stream << "<!DOCTYPE html>\n";
	auth_register_tmp_stream << "<html lang=\"ru\">\n";
	auth_register_tmp_stream << "<head>\n";
	auth_register_tmp_stream << "    <meta charset=\"UTF-8\" />\n";
	auth_register_tmp_stream << "    <title>Регистрация - Financial Manager</title>\n";
	auth_register_tmp_stream << "    <link rel=\"stylesheet\" href=\"https://unpkg.com/sakura.css/css/sakura.css\" />\n";
	auth_register_tmp_stream << "</head>\n";
	auth_register_tmp_stream << "<body>\n";
	auth_register_tmp_stream << "    <h1>Регистрация</h1>\n";
	auth_register_tmp_stream << "    <form id=\"registerForm\">\n";
	auth_register_tmp_stream << "        <label>Имя\n";
	auth_register_tmp_stream << "            <input type=\"text\" name=\"name\" required />\n";
	auth_register_tmp_stream << "        </label>\n";
	auth_register_tmp_stream << "        <label>Email\n";
	auth_register_tmp_stream << "            <input type=\"email\" name=\"email\" required />\n";
	auth_register_tmp_stream << "        </label>\n";
	auth_register_tmp_stream << "        <label>Пароль\n";
	auth_register_tmp_stream << "            <input type=\"password\" name=\"password\" required />\n";
	auth_register_tmp_stream << "        </label>\n";
	auth_register_tmp_stream << "        <button type=\"submit\">Зарегистрироваться</button>\n";
	auth_register_tmp_stream << "    </form>\n";
	auth_register_tmp_stream << "    <p id=\"message\"></p>\n";
	auth_register_tmp_stream << "    <script>\n";
	auth_register_tmp_stream << "        document.getElementById('registerForm').addEventListener('submit', async (e) => {\n";
	auth_register_tmp_stream << "            e.preventDefault();\n";
	auth_register_tmp_stream << "            const form = e.target;\n";
	auth_register_tmp_stream << "            const body = {\n";
	auth_register_tmp_stream << "                name: form.name.value,\n";
	auth_register_tmp_stream << "                email: form.email.value,\n";
	auth_register_tmp_stream << "                password: form.password.value\n";
	auth_register_tmp_stream << "            };\n";
	auth_register_tmp_stream << "            try {\n";
	auth_register_tmp_stream << "                const resp = await fetch('/api/auth/register', {\n";
	auth_register_tmp_stream << "                    method: 'POST',\n";
	auth_register_tmp_stream << "                    headers: { 'Content-Type': 'application/json' },\n";
	auth_register_tmp_stream << "                    body: JSON.stringify(body)\n";
	auth_register_tmp_stream << "                });\n";
	auth_register_tmp_stream << "                if (resp.ok) {\n";
	auth_register_tmp_stream << "                    document.getElementById('message').textContent = 'Регистрация успешна, перенаправление на страницу входа...';\n";
	auth_register_tmp_stream << "                    setTimeout(() => {\n";
	auth_register_tmp_stream << "                        window.location.href = '/auth/login';\n";
	auth_register_tmp_stream << "                    }, 800);\n";
	auth_register_tmp_stream << "                } else {\n";
	auth_register_tmp_stream << "                    const text = await resp.text();\n";
	auth_register_tmp_stream << "                    document.getElementById('message').textContent = 'Ошибка: ' + text;\n";
	auth_register_tmp_stream << "                }\n";
	auth_register_tmp_stream << "            } catch (e) {\n";
	auth_register_tmp_stream << "                document.getElementById('message').textContent = 'Ошибка сети';\n";
	auth_register_tmp_stream << "            }\n";
	auth_register_tmp_stream << "        });\n";
	auth_register_tmp_stream << "    </script>\n";
	auth_register_tmp_stream << "</body>\n";
	auth_register_tmp_stream << "</html>\n";
auth_register_tmp_stream<<"\n";
auth_register_tmp_stream<<"\n";
if(layoutName.empty())
{
std::string ret{std::move(auth_register_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = auth_register_view_data;
auto str = std::move(auth_register_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
