/**
 *
 *  Budgets.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Budgets.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::financial_manager;

const std::string Budgets::Cols::_id = "\"id\"";
const std::string Budgets::Cols::_id_user = "\"id_user\"";
const std::string Budgets::Cols::_id_category = "\"id_category\"";
const std::string Budgets::Cols::_month = "\"month\"";
const std::string Budgets::Cols::_year = "\"year\"";
const std::string Budgets::Cols::_limit_amount = "\"limit_amount\"";
const std::string Budgets::Cols::_created_at = "\"created_at\"";
const std::string Budgets::primaryKeyName = "id";
const bool Budgets::hasPrimaryKey = true;
const std::string Budgets::tableName = "\"budgets\"";

const std::vector<typename Budgets::MetaData> Budgets::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"id_user","int32_t","integer",4,0,0,1},
{"id_category","int32_t","integer",4,0,0,1},
{"month","int32_t","integer",4,0,0,1},
{"year","int32_t","integer",4,0,0,1},
{"limit_amount","std::string","numeric",0,0,0,1},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &Budgets::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Budgets::Budgets(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["id_user"].isNull())
        {
            idUser_=std::make_shared<int32_t>(r["id_user"].as<int32_t>());
        }
        if(!r["id_category"].isNull())
        {
            idCategory_=std::make_shared<int32_t>(r["id_category"].as<int32_t>());
        }
        if(!r["month"].isNull())
        {
            month_=std::make_shared<int32_t>(r["month"].as<int32_t>());
        }
        if(!r["year"].isNull())
        {
            year_=std::make_shared<int32_t>(r["year"].as<int32_t>());
        }
        if(!r["limit_amount"].isNull())
        {
            limitAmount_=std::make_shared<std::string>(r["limit_amount"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            idUser_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            idCategory_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            month_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            year_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            limitAmount_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Budgets::Budgets(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idCategory_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            month_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            year_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            limitAmount_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Budgets::Budgets(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["id_user"].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson["id_user"].asInt64());
        }
    }
    if(pJson.isMember("id_category"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["id_category"].isNull())
        {
            idCategory_=std::make_shared<int32_t>((int32_t)pJson["id_category"].asInt64());
        }
    }
    if(pJson.isMember("month"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["month"].isNull())
        {
            month_=std::make_shared<int32_t>((int32_t)pJson["month"].asInt64());
        }
    }
    if(pJson.isMember("year"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["year"].isNull())
        {
            year_=std::make_shared<int32_t>((int32_t)pJson["year"].asInt64());
        }
    }
    if(pJson.isMember("limit_amount"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["limit_amount"].isNull())
        {
            limitAmount_=std::make_shared<std::string>(pJson["limit_amount"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Budgets::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idCategory_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            month_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            year_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            limitAmount_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Budgets::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_user"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["id_user"].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson["id_user"].asInt64());
        }
    }
    if(pJson.isMember("id_category"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["id_category"].isNull())
        {
            idCategory_=std::make_shared<int32_t>((int32_t)pJson["id_category"].asInt64());
        }
    }
    if(pJson.isMember("month"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["month"].isNull())
        {
            month_=std::make_shared<int32_t>((int32_t)pJson["month"].asInt64());
        }
    }
    if(pJson.isMember("year"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["year"].isNull())
        {
            year_=std::make_shared<int32_t>((int32_t)pJson["year"].asInt64());
        }
    }
    if(pJson.isMember("limit_amount"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["limit_amount"].isNull())
        {
            limitAmount_=std::make_shared<std::string>(pJson["limit_amount"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &Budgets::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Budgets::getId() const noexcept
{
    return id_;
}
void Budgets::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Budgets::PrimaryKeyType & Budgets::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &Budgets::getValueOfIdUser() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idUser_)
        return *idUser_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Budgets::getIdUser() const noexcept
{
    return idUser_;
}
void Budgets::setIdUser(const int32_t &pIdUser) noexcept
{
    idUser_ = std::make_shared<int32_t>(pIdUser);
    dirtyFlag_[1] = true;
}

const int32_t &Budgets::getValueOfIdCategory() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idCategory_)
        return *idCategory_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Budgets::getIdCategory() const noexcept
{
    return idCategory_;
}
void Budgets::setIdCategory(const int32_t &pIdCategory) noexcept
{
    idCategory_ = std::make_shared<int32_t>(pIdCategory);
    dirtyFlag_[2] = true;
}

const int32_t &Budgets::getValueOfMonth() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(month_)
        return *month_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Budgets::getMonth() const noexcept
{
    return month_;
}
void Budgets::setMonth(const int32_t &pMonth) noexcept
{
    month_ = std::make_shared<int32_t>(pMonth);
    dirtyFlag_[3] = true;
}

const int32_t &Budgets::getValueOfYear() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(year_)
        return *year_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Budgets::getYear() const noexcept
{
    return year_;
}
void Budgets::setYear(const int32_t &pYear) noexcept
{
    year_ = std::make_shared<int32_t>(pYear);
    dirtyFlag_[4] = true;
}

const std::string &Budgets::getValueOfLimitAmount() const noexcept
{
    static const std::string defaultValue = std::string();
    if(limitAmount_)
        return *limitAmount_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Budgets::getLimitAmount() const noexcept
{
    return limitAmount_;
}
void Budgets::setLimitAmount(const std::string &pLimitAmount) noexcept
{
    limitAmount_ = std::make_shared<std::string>(pLimitAmount);
    dirtyFlag_[5] = true;
}
void Budgets::setLimitAmount(std::string &&pLimitAmount) noexcept
{
    limitAmount_ = std::make_shared<std::string>(std::move(pLimitAmount));
    dirtyFlag_[5] = true;
}

const ::trantor::Date &Budgets::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Budgets::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Budgets::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[6] = true;
}

void Budgets::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Budgets::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_user",
        "id_category",
        "month",
        "year",
        "limit_amount",
        "created_at"
    };
    return inCols;
}

void Budgets::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdUser())
        {
            binder << getValueOfIdUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdCategory())
        {
            binder << getValueOfIdCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMonth())
        {
            binder << getValueOfMonth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getYear())
        {
            binder << getValueOfYear();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLimitAmount())
        {
            binder << getValueOfLimitAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Budgets::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void Budgets::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdUser())
        {
            binder << getValueOfIdUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdCategory())
        {
            binder << getValueOfIdCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMonth())
        {
            binder << getValueOfMonth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getYear())
        {
            binder << getValueOfYear();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLimitAmount())
        {
            binder << getValueOfLimitAmount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Budgets::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdUser())
    {
        ret["id_user"]=getValueOfIdUser();
    }
    else
    {
        ret["id_user"]=Json::Value();
    }
    if(getIdCategory())
    {
        ret["id_category"]=getValueOfIdCategory();
    }
    else
    {
        ret["id_category"]=Json::Value();
    }
    if(getMonth())
    {
        ret["month"]=getValueOfMonth();
    }
    else
    {
        ret["month"]=Json::Value();
    }
    if(getYear())
    {
        ret["year"]=getValueOfYear();
    }
    else
    {
        ret["year"]=Json::Value();
    }
    if(getLimitAmount())
    {
        ret["limit_amount"]=getValueOfLimitAmount();
    }
    else
    {
        ret["limit_amount"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string Budgets::toString() const
{
    return toJson().toStyledString();
}

Json::Value Budgets::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getIdUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfIdUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIdCategory())
            {
                ret[pMasqueradingVector[2]]=getValueOfIdCategory();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getMonth())
            {
                ret[pMasqueradingVector[3]]=getValueOfMonth();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getYear())
            {
                ret[pMasqueradingVector[4]]=getValueOfYear();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getLimitAmount())
            {
                ret[pMasqueradingVector[5]]=getValueOfLimitAmount();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[6]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdUser())
    {
        ret["id_user"]=getValueOfIdUser();
    }
    else
    {
        ret["id_user"]=Json::Value();
    }
    if(getIdCategory())
    {
        ret["id_category"]=getValueOfIdCategory();
    }
    else
    {
        ret["id_category"]=Json::Value();
    }
    if(getMonth())
    {
        ret["month"]=getValueOfMonth();
    }
    else
    {
        ret["month"]=Json::Value();
    }
    if(getYear())
    {
        ret["year"]=getValueOfYear();
    }
    else
    {
        ret["year"]=Json::Value();
    }
    if(getLimitAmount())
    {
        ret["limit_amount"]=getValueOfLimitAmount();
    }
    else
    {
        ret["limit_amount"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool Budgets::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("id_user"))
    {
        if(!validJsonOfField(1, "id_user", pJson["id_user"], err, true))
            return false;
    }
    else
    {
        err="The id_user column cannot be null";
        return false;
    }
    if(pJson.isMember("id_category"))
    {
        if(!validJsonOfField(2, "id_category", pJson["id_category"], err, true))
            return false;
    }
    else
    {
        err="The id_category column cannot be null";
        return false;
    }
    if(pJson.isMember("month"))
    {
        if(!validJsonOfField(3, "month", pJson["month"], err, true))
            return false;
    }
    else
    {
        err="The month column cannot be null";
        return false;
    }
    if(pJson.isMember("year"))
    {
        if(!validJsonOfField(4, "year", pJson["year"], err, true))
            return false;
    }
    else
    {
        err="The year column cannot be null";
        return false;
    }
    if(pJson.isMember("limit_amount"))
    {
        if(!validJsonOfField(5, "limit_amount", pJson["limit_amount"], err, true))
            return false;
    }
    else
    {
        err="The limit_amount column cannot be null";
        return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(6, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool Budgets::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Budgets::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("id_user"))
    {
        if(!validJsonOfField(1, "id_user", pJson["id_user"], err, false))
            return false;
    }
    if(pJson.isMember("id_category"))
    {
        if(!validJsonOfField(2, "id_category", pJson["id_category"], err, false))
            return false;
    }
    if(pJson.isMember("month"))
    {
        if(!validJsonOfField(3, "month", pJson["month"], err, false))
            return false;
    }
    if(pJson.isMember("year"))
    {
        if(!validJsonOfField(4, "year", pJson["year"], err, false))
            return false;
    }
    if(pJson.isMember("limit_amount"))
    {
        if(!validJsonOfField(5, "limit_amount", pJson["limit_amount"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(6, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool Budgets::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Budgets::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
