/**
 *
 *  FamilyMembers.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "FamilyMembers.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::financial_manager;

const std::string FamilyMembers::Cols::_id = "\"id\"";
const std::string FamilyMembers::Cols::_id_family = "\"id_family\"";
const std::string FamilyMembers::Cols::_id_user = "\"id_user\"";
const std::string FamilyMembers::Cols::_joined_at = "\"joined_at\"";
const std::string FamilyMembers::primaryKeyName = "id";
const bool FamilyMembers::hasPrimaryKey = true;
const std::string FamilyMembers::tableName = "\"family_members\"";

const std::vector<typename FamilyMembers::MetaData> FamilyMembers::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"id_family","int64_t","bigint",8,0,0,1},
{"id_user","int64_t","bigint",8,0,0,1},
{"joined_at","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &FamilyMembers::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
FamilyMembers::FamilyMembers(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["id_family"].isNull())
        {
            idFamily_=std::make_shared<int64_t>(r["id_family"].as<int64_t>());
        }
        if(!r["id_user"].isNull())
        {
            idUser_=std::make_shared<int64_t>(r["id_user"].as<int64_t>());
        }
        if(!r["joined_at"].isNull())
        {
            auto timeStr = r["joined_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                joinedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            idFamily_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            idUser_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                joinedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

FamilyMembers::FamilyMembers(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idFamily_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idUser_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                joinedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

FamilyMembers::FamilyMembers(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_family"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["id_family"].isNull())
        {
            idFamily_=std::make_shared<int64_t>((int64_t)pJson["id_family"].asInt64());
        }
    }
    if(pJson.isMember("id_user"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["id_user"].isNull())
        {
            idUser_=std::make_shared<int64_t>((int64_t)pJson["id_user"].asInt64());
        }
    }
    if(pJson.isMember("joined_at"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["joined_at"].isNull())
        {
            auto timeStr = pJson["joined_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                joinedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void FamilyMembers::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idFamily_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idUser_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                joinedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void FamilyMembers::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("id_family"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["id_family"].isNull())
        {
            idFamily_=std::make_shared<int64_t>((int64_t)pJson["id_family"].asInt64());
        }
    }
    if(pJson.isMember("id_user"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["id_user"].isNull())
        {
            idUser_=std::make_shared<int64_t>((int64_t)pJson["id_user"].asInt64());
        }
    }
    if(pJson.isMember("joined_at"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["joined_at"].isNull())
        {
            auto timeStr = pJson["joined_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                joinedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &FamilyMembers::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &FamilyMembers::getId() const noexcept
{
    return id_;
}
void FamilyMembers::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename FamilyMembers::PrimaryKeyType & FamilyMembers::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &FamilyMembers::getValueOfIdFamily() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(idFamily_)
        return *idFamily_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &FamilyMembers::getIdFamily() const noexcept
{
    return idFamily_;
}
void FamilyMembers::setIdFamily(const int64_t &pIdFamily) noexcept
{
    idFamily_ = std::make_shared<int64_t>(pIdFamily);
    dirtyFlag_[1] = true;
}

const int64_t &FamilyMembers::getValueOfIdUser() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(idUser_)
        return *idUser_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &FamilyMembers::getIdUser() const noexcept
{
    return idUser_;
}
void FamilyMembers::setIdUser(const int64_t &pIdUser) noexcept
{
    idUser_ = std::make_shared<int64_t>(pIdUser);
    dirtyFlag_[2] = true;
}

const ::trantor::Date &FamilyMembers::getValueOfJoinedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(joinedAt_)
        return *joinedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &FamilyMembers::getJoinedAt() const noexcept
{
    return joinedAt_;
}
void FamilyMembers::setJoinedAt(const ::trantor::Date &pJoinedAt) noexcept
{
    joinedAt_ = std::make_shared<::trantor::Date>(pJoinedAt);
    dirtyFlag_[3] = true;
}

void FamilyMembers::updateId(const uint64_t id)
{
}

const std::vector<std::string> &FamilyMembers::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_family",
        "id_user",
        "joined_at"
    };
    return inCols;
}

void FamilyMembers::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdFamily())
        {
            binder << getValueOfIdFamily();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdUser())
        {
            binder << getValueOfIdUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getJoinedAt())
        {
            binder << getValueOfJoinedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> FamilyMembers::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void FamilyMembers::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdFamily())
        {
            binder << getValueOfIdFamily();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdUser())
        {
            binder << getValueOfIdUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getJoinedAt())
        {
            binder << getValueOfJoinedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value FamilyMembers::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdFamily())
    {
        ret["id_family"]=(Json::Int64)getValueOfIdFamily();
    }
    else
    {
        ret["id_family"]=Json::Value();
    }
    if(getIdUser())
    {
        ret["id_user"]=(Json::Int64)getValueOfIdUser();
    }
    else
    {
        ret["id_user"]=Json::Value();
    }
    if(getJoinedAt())
    {
        ret["joined_at"]=getJoinedAt()->toDbStringLocal();
    }
    else
    {
        ret["joined_at"]=Json::Value();
    }
    return ret;
}

std::string FamilyMembers::toString() const
{
    return toJson().toStyledString();
}

Json::Value FamilyMembers::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getIdFamily())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfIdFamily();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIdUser())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfIdUser();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getJoinedAt())
            {
                ret[pMasqueradingVector[3]]=getJoinedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdFamily())
    {
        ret["id_family"]=(Json::Int64)getValueOfIdFamily();
    }
    else
    {
        ret["id_family"]=Json::Value();
    }
    if(getIdUser())
    {
        ret["id_user"]=(Json::Int64)getValueOfIdUser();
    }
    else
    {
        ret["id_user"]=Json::Value();
    }
    if(getJoinedAt())
    {
        ret["joined_at"]=getJoinedAt()->toDbStringLocal();
    }
    else
    {
        ret["joined_at"]=Json::Value();
    }
    return ret;
}

bool FamilyMembers::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("id_family"))
    {
        if(!validJsonOfField(1, "id_family", pJson["id_family"], err, true))
            return false;
    }
    else
    {
        err="The id_family column cannot be null";
        return false;
    }
    if(pJson.isMember("id_user"))
    {
        if(!validJsonOfField(2, "id_user", pJson["id_user"], err, true))
            return false;
    }
    else
    {
        err="The id_user column cannot be null";
        return false;
    }
    if(pJson.isMember("joined_at"))
    {
        if(!validJsonOfField(3, "joined_at", pJson["joined_at"], err, true))
            return false;
    }
    return true;
}
bool FamilyMembers::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool FamilyMembers::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("id_family"))
    {
        if(!validJsonOfField(1, "id_family", pJson["id_family"], err, false))
            return false;
    }
    if(pJson.isMember("id_user"))
    {
        if(!validJsonOfField(2, "id_user", pJson["id_user"], err, false))
            return false;
    }
    if(pJson.isMember("joined_at"))
    {
        if(!validJsonOfField(3, "joined_at", pJson["joined_at"], err, false))
            return false;
    }
    return true;
}
bool FamilyMembers::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool FamilyMembers::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
